### PR TITLE
style(Button): add mixin and improve styling for play/pause button

### LINKED ISSUE #83: beta.quran.com - icon placement
Al Salam Alaikom,

The white triangle is not aligned properly inside the circle.  This issue was checked on both Edge and firefox, and it appears on both browsers. 

icon-centering

### PR DESCRIPTION
**Pull request by AshNaz87**
@naveed-ahmad Should close #83

Don't have access to the database, so wasn't able to take screenshots locally

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
@AshNaz87 We've included a mini db dump link in readme. 

https://drive.google.com/drive/folders/1tkm0nYVTZaOYSbFcSJIc6Lq1rM-PIUBy

Can you please load this dump and post the screenshots?

**Comment by AshNaz87** [comment]
@naveed-ahmad Thanks for that

I now get an error

```bash
undefined method `verse_number' for nil:NilClass excluded from capture: DSN not set

ActionView::Template::Error (undefined method `verse_number' for nil:NilClass):
    11:     <%= chapter_next_page_link %>
    12:   <% end %>
    13:
    14:   <% if @presenter.continue? %>
    15:     <%= link_to chapter_path(@presenter.chapter), class: 'btn btn-outline-primary' do %>
    16:       <%= _t('chapters.read_full') %>
    17:     <% end %>
```

**Comment by AshNaz87** [comment]
That was for `/ayatul-kursi`

**Comment by naveed-ahmad** [comment]
Minidump included first 20 ayahs of every surah. Ayat ul kursi is 2:255

**Comment by AshNaz87** [comment]
Thanks, just rebased and pushed

Screenshot 2020-04-01 at 15 47 29
Screenshot 2020-04-01 at 15 51 26
Screenshot 2020-04-01 at 15 51 48
Screenshot 2020-04-01 at 15 51 58
Screenshot 2020-04-01 at 15 56 22

**Comment by AshNaz87** [comment]
Actually, this is trickier than I originally thought

My go-to browser is Firefox. Renders differently on Chrome

**Comment by naveed-ahmad** [comment]
@AshNaz87 also try to remove the translations, we've slightly different layout for mobile when there is no translation. 

https://tinyurl.com/tq7jrvj

**Pull request closed without merging**
