### PR TITLE
first step to translate to Portuguese Brazil

### PR DESCRIPTION
**Pull request by carlosdelfino**

### CODE REVIEW

**Comment by naveed-ahmad** [comment]
JazakAllah kharian for PR, we're using translation.io for managing locals. Sent you the invitation and please move these translation to https://translation.io/quran

Once you're done, ill sync it with rails app. Can't push locals directly into repo, this will lost with next sync with translation.io

**Comment by naveed-ahmad** [comment]
https://translation.io/quran/quran

**Comment by carlosdelfino** [comment]
> https://translation.io/quran/quran

please add too professor@carlosdelfino.eti.br (I use two emails.)

**Comment by carlosdelfino** [comment]
I made a little mistake at first, but I believe everything is now ready.

Thankful.

**Pull request closed without merging**
