### PR TITLE
fixed broken icon. issue: #422

### PR DESCRIPTION
**Pull request by Yuniac**
The class `quran-icon` was half missing, only the word `icon` was given to the `span` element which on its own do nothing as far as I understood.
I fixed the broken icon by fixing the broken class name. However, I noticed that the icon isn't aligned vertically, now I tried fixing it locally by using `vertical-align: middle;` which worked but I wasn't quite sure how to go about it in the project as a whole, editing the `quran-icon` class would affect every single icon that has it, and after testing that, it had side effects on other icons that were perfectly fine so I will leave that to you.

### CODE REVIEW

**Review by naveed-ahmad — APPROVED** [review]

**Comment by naveed-ahmad** [comment]
Thanks!

**Comment by naveed-ahmad** [comment]
We can ignore vertical-align, the frontend soon will be replaced with this https://github.com/quran/quran.com-frontend-next

**Comment by zpaya** [comment]
Wow. I thought of fixing myself but lost as I am into QA and left with a bug for developer :)

**Comment by Yuniac** [comment]
> 
> 
> Wow. I thought of fixing myself but lost as I am into QA and left with a bug for developer :)

No problem I was happy to do it myself 🙂

**Pull request merged**
