### PR TITLE
Feature/issue 327

### PR DESCRIPTION
**Pull request by Shemsedin**
Fixes this issue https://github.com/quran/quran.com-frontend-v2/issues/327

### CODE REVIEW

**Comment by Shemsedin** [comment]
@naveed-ahmad has this been merged in as the issue hasn't been fixed on live - the user also reported that this hasn't yet ben fixed

**Comment by ahmedre** [comment]
this hasn't been merged yet

**Comment by Shemsedin** [comment]
yeh I can see that - I am asking if this can be merged as the fix need to be deployed on live

**Comment by naveed-ahmad** [comment]
@Shemsedin closing this. This was a translation issue, fixed on translation.io and resynced.

**Pull request closed without merging**
